export const EXECUTE_PAYMENT='EXECUTE_PAYMENT';
export const PAYMENT_STATUS='PAYMENT_STATUS';
export const CANCEL_EXECUTED_PAYMENTS='CANCEL_EXECUTED_PAYMENTS';
export const CHOOSE_EMPLYEES='CHOOSE_EMPLYEES'
